### ISSUE TITLE
Create basic contract for ChronoMint

### ISSUE THREAD

**Issue by Chronoctopus** [ChronoBank/ChronoMint#2]
Store addresses of all LH contracts, TIME contract, Rewards contract, Security Guarantee and Liquidity funds contracts, all LOCs contracts addresses.

**Comment by Deltamekong** [comment]
Store addresses of all LH contracts, TIME contract, Rewards contract, Security Guarantee and Liquidity funds contracts, all LOCs contracts addresses.
