### ISSUE TITLE
Create basic LOC contract

### ISSUE THREAD

**Issue by Chronoctopus** [ChronoBank/ChronoMint#3]
Store:
- LOC business title (string)
- business website (string)
- business status (ENUM: active, suspended, bankrupt)
- LOC controller address
- amount allowed to issue
- amount issued
- amount redeemed
- IPFS hash of public contract
- percents from LH issuance that go to the Security Guarantee and Liquidity funds
- etc.

**Comment by Deltamekong** [comment]
Store:

LOC business title (string)
business website (string)
business status (ENUM: active, suspended, bankrupt)
LOC controller address
amount allowed to issue
amount issued
amount redeemed
IPFS hash of public contract
percents from LH issuance that go to the Security Guarantee and Liquidity funds
etc.
