### ISSUE TITLE
Looks like LaborHourToken.sol is missing

### ISSUE THREAD

**Issue by gutsal-arsen** [ChronoBank/ChronoMint#6]
## Issue

It looks like LaborHourToken.sol is missing (most possible not added to repo).

## Steps to Reproduce
```
git clone https://github.com/ChronoBank/ChronoMint  
cd ChronoMint
npm install
npm build
npm start
```
## Expected Behavior

Think something should be running on some port ;)

## Actual Results

![xxx](https://cloud.githubusercontent.com/assets/1643117/21446859/8b4c401c-c8d4-11e6-8262-1a19d09517d2.png)

## Environment

* Operating System:
```
uname -a
Linux capitan 4.8.10-gentoo #1 SMP Tue Nov 22 15:25:37 EET 2016 x86_64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz GenuineIntel GNU/Linux
```
* Truffle version:
```
archer@capitan ~ $ truffle -v
Truffle v2.1.1 - a development framework for Ethereum
```
* Testrpc version:
```
archer@capitan ~ $ testrpc -v
EthereumJS TestRPC v3.0.3
```

* Ethereum client:
```
archer@capitan ~ $ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
ethereum/client-cpp           latest              12a48ab69603        2 days ago          1.234 GB

```
* node version:
```
archer@capitan ~ $ node -v
v6.3.0
```
* npm version:
```
archer@capitan ~ $ npm -v
3.10.8
```

**Comment by gmikeska** [comment]
Pushed! Thanks!

**Comment by gutsal-arsen** [comment]
Which branch then?
Guess it's broken feature. Better to push it to `master` branch.

![xxx](https://cloud.githubusercontent.com/assets/1643117/21452113/352f9fba-c90d-11e6-94b8-5c5b44950833.png)

**Comment by gutsal-arsen** [comment]
Well, looks like this issue has been resolved, but there's another one:

![xxx](https://cloud.githubusercontent.com/assets/1643117/21456525/58cbe2f2-c931-11e6-973f-9a5b62237754.png)

Other window was running `testprc`
